### ISSUE TITLE
Web installer hangs when connecting to WiFi

### ISSUE THREAD

**Issue by sblantipodi** [tasmota/install#16] opened 2023-07-09 14:04 UTC
Hi,
from time to time, when I install tasmota on an ESP8266 using the web installer, 
it hangs when configuring the wifi...

![image](https://github.com/tasmota/install/assets/4722227/b3d05b5a-cb2d-4cd8-8a4c-59611390df5b)

I neet to refresh the page and retry connecting to wifi, sometimes it requires 3 or 4 tentatives.

This does not happen on ESP32.

Is this a known issue?

**Comment by Staars** [comment] 2023-07-09 16:27
Chances are great, that this is unrelated to the webflasher, but it is impossible to really know without seeing the logs.
Basically your ESP8266 can not connect to your AP, which is not totally uncommon with these kinds of devices.
If the same ESP8266 never has connection issues in Tasmota later on or you can commission this device with i.e. with ESP-Home with their implementation of the web-flasher in 10 of 10 tries, then it probably is related.
But even then it will be close to impossible to figure out the reason with the amount of data we have (and this not your fault!), so we can only put it on the list of „things to keep an eye on“.

**Comment by sblantipodi** [comment] 2023-07-09 22:04
The only things I can say is that the device is 100% stable once connected and rarely loose WiFi connection.
Same error happen with the esp home web installer when installing esp home.

I tried the wled web installer and that web installer works well 100% of the time.
Don't know how this is possible but the wled one is the best I tried on esp8266.

**Comment by Jason2866** [comment] 2023-10-13 14:25
Closing since not reproducable

**Closed as completed** 2023-10-13 14:27 UTC
